<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="HydraulicValve" Id="{52b97062-b094-41f2-9637-f563a04dcc55}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HydraulicValve
VAR_INPUT
	bvPosDir	: BOOL;
	bvNegDir	: BOOL;
	command		: REAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	posDir	:	Solenoid();
	negDir	:	Solenoid(); 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>